/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Labib Ashrori
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDataJenisKamera = new javax.swing.JMenuItem();
        mnuDataKamera = new javax.swing.JMenuItem();
        mnuDataKaryawan = new javax.swing.JMenuItem();
        mnuDataPelanggan = new javax.swing.JMenuItem();
        mnuDataSewa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuLaporanDataKamera = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rental Kamera");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        mnuDataJenisKamera.setText("Data Jenis Kamera");
        mnuDataJenisKamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataJenisKameraActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDataJenisKamera);

        mnuDataKamera.setText("Data Kamera");
        mnuDataKamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataKameraActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDataKamera);

        mnuDataKaryawan.setText("Data Karyawan");
        mnuDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDataKaryawan);

        mnuDataPelanggan.setText("Data Pelanggan");
        mnuDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDataPelanggan);

        mnuDataSewa.setText("Data Sewa");
        mnuDataSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataSewaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDataSewa);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        mnuLaporanDataKamera.setText("Laporan Data Kamera");
        mnuLaporanDataKamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaporanDataKameraActionPerformed(evt);
            }
        });
        jMenu3.add(mnuLaporanDataKamera);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Bantuan");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        mnuTentang.setText("Tentang");
        mnuTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTentangActionPerformed(evt);
            }
        });
        jMenu4.add(mnuTentang);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDataJenisKameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataJenisKameraActionPerformed
        // TODO add your handling code here:
        DataJenisKamera DataJenisKamera = new DataJenisKamera();
        jDesktopPane1.add(DataJenisKamera);
        DataJenisKamera.setVisible(true);
    }//GEN-LAST:event_mnuDataJenisKameraActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuDataKameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataKameraActionPerformed
        // TODO add your handling code here:
        DataKamera DataKamera = new DataKamera();
        jDesktopPane1.add(DataKamera);
        DataKamera.setVisible(true);
    }//GEN-LAST:event_mnuDataKameraActionPerformed

    private void mnuDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataKaryawanActionPerformed
        // TODO add your handling code here:
        DataKaryawan DataKaryawan = new DataKaryawan();
        jDesktopPane1.add(DataKaryawan);
        DataKaryawan.setVisible(true);
    }//GEN-LAST:event_mnuDataKaryawanActionPerformed

    private void mnuDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataPelangganActionPerformed
        // TODO add your handling code here:
        DataPelanggan DataPelanggan = new DataPelanggan();
        jDesktopPane1.add(DataPelanggan);
        DataPelanggan.setVisible(true);
    }//GEN-LAST:event_mnuDataPelangganActionPerformed

    private void mnuDataSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataSewaActionPerformed
        // TODO add your handling code here:
        DataSewa DataSewa = new DataSewa();
        jDesktopPane1.add(DataSewa);
        DataSewa.setVisible(true);
    }//GEN-LAST:event_mnuDataSewaActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void mnuTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTentangActionPerformed
        // TODO add your handling code here:
        Tentang Tentang = new Tentang();
        jDesktopPane1.add(Tentang);
        Tentang.setVisible(true);
    }//GEN-LAST:event_mnuTentangActionPerformed

    private void mnuLaporanDataKameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaporanDataKameraActionPerformed
        // TODO add your handling code here:
        LaporanDataKamera LaporanDataKamera = new LaporanDataKamera();
        jDesktopPane1.add(LaporanDataKamera);
        LaporanDataKamera.setVisible(true);
    }//GEN-LAST:event_mnuLaporanDataKameraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuDataJenisKamera;
    private javax.swing.JMenuItem mnuDataKamera;
    private javax.swing.JMenuItem mnuDataKaryawan;
    private javax.swing.JMenuItem mnuDataPelanggan;
    private javax.swing.JMenuItem mnuDataSewa;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLaporanDataKamera;
    private javax.swing.JMenuItem mnuTentang;
    // End of variables declaration//GEN-END:variables
}
